import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



import { Toaster } from "@/components/ui/sonner";

import ProviderAuth from "@/providers/SessionProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import SocketProvider from "@/providers/SocketProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  


  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={` h-full antialiased font-manrope`}

    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
        <ProviderAuth>
<SocketProvider/>
          {children}
          <Toaster />
        </ProviderAuth>
        </TooltipProvider>
      </body>
    </html>
  );
}
